### ISSUE TITLE
Empty proxy variables are not handled properly

### ISSUE THREAD

**Issue by seventyeight** [typings/core#101]
I'm used to unset my proxy settings like this: `env http_proxy='' https_proxy='' cmd`. It works with i.e.: **npm** or **brew**, but it does not with **typings install**. The output is: `message an HTTP(S) proxy server `host` and `port` must be specified!`
If i delete the variables from the shell environment, the installation runs fine. 
Any ideas how to solve it?

**Comment by blakeembrey** [comment]
It definitely works fine. It's a simple boolean check. Sounds like an issue on your end, perhaps there's an upper-case version of `HTTP_PROXY` available? Why not just do `NO_PROXY="*"`?

**Comment by blakeembrey** [comment]
Actually, you could be correct - is this when querying a HTTPS url? I noticed it's doing a null check in my code and can do a patch for truthy instead. 

Reference: https://github.com/blakeembrey/popsicle-proxy-agent/blob/master/src/index.ts#L50. Does that sound like the issue?

**Comment by blakeembrey** [comment]
Is `NO_PROXY` a good solution for now? I can back-port a release for you, if you'd like.

**Comment by seventyeight** [comment]
Yes, `no_proxy` seems fine. Thanks a lot for the quick solution!

**Comment by blakeembrey** [comment]
Awesome! 😄
