### ISSUE TITLE
Installing package with globalDependencies outputs "undefined" instead of the package name

### ISSUE THREAD

**Issue by janb87** [typings/core#115]
I get this message when installing typings which has global dependencies.

```
typings INFO globaldependencies "undefined" lists global dependencies on "react", "react-dom" and should be installed
```

**Comment by unional** [comment]
That just means you have global dependencies `react` and `react-dom`. `undefined` because your `typings.json/name` is not defined.

**Comment by unional** [comment]
Also, you can post in https://github.com/typings/typings/issue in the future. That's the main place to post issues.

**Comment by blakeembrey** [comment]
Can you point me to the command you used? I'll quickly review if there's a way we can get the name during this step.

**Comment by janb87** [comment]
@blakeembrey 

The command I run is:

```
typings install file:./node_modules/my-project/typings.json --save --global
```

Typings.json of my-project looks like:

```
{
  "name": "my-project",
  "global": true,
  "files": [
    "dist/index.d.ts"
  ],
  "globalDependencies": {
    "react": "registry:dt/react#0.14.0+20160602125106",
    "react-dom": "registry:dt/react-dom#0.14.0+20160412154040"
  }
}
```

I do have a project name set so I was expecting to see:
```
typings INFO globaldependencies "my-project" lists global dependencies on "react", "react-dom" and should be installed
```

**Comment by vitaly-t** [comment]
Any update here?

**Comment by unional** [comment]
The "undefined" part is because `github:` => `file:` does not read name from the `typings.json`. It relies on user input: `typings install pg-promise=github:vitaly-t/pg-promise ...`.
https://github.com/typings/core/blob/master/src/lib/dependencies.ts#L191

**Comment by unional** [comment]
The "undefined" is cause by the following line:
https://github.com/typings/core/blob/master/src/lib/dependencies.ts#L467
It does not use `config.name` when it exists.
