### ISSUE TITLE
Implement jspm: discussion

### ISSUE THREAD

**Issue by unional** [typings/core#116]
This issue is create to discuss any issue related to this feature.
### syntax

``` sh
# simplest for the user
# require `parse.ts` to read `package.json`, then read either `config.js` or `jspm.config.js`
jspm:foobar

# base of folder structure, map to `jspm_packages/npm/foobar@1.2.3/`
# still require to read `package.json` because `jspm_packages` is configurable.
# require less parsing of `package.json` and `config.js`
jspm:npm/foobar@1.2.3
jspm:git/org/repo@2.3.4
```

Will try to do the first syntax, which depends on...
### jspm module metadata discovery

...in discussion...
### dependency discovery

...in discussion...

**Comment by unional** [comment]
### syntax 

There are several syntax to choose from:

```sh
# simplest for the user
# require `parse.ts` to read `package.json`, then read either `config.js` or `jspm.config.js`
jspm:foobar

# better align with `jspm install npm:foobar`
# require `parse.ts` to read `package.json`, then read either `config.js` or `jspm.config.js`
jspm:npm:foobar
jspm:git:org/repo

# sightly better to the eye. more align with current scheme. deviate from jspm syntax
# require `parse.ts` to read `package.json`, then read either `config.js` or `jspm.config.js`
jspm:npm/foobar
jspm:git/org/repo

# base of folder structure, map to `jspm_packages/npm/foobar@1.2.3/`
# still require to read `package.json` because `jspm_packages` is configurable.
# require less parsing of `package.json` and `config.js`
jspm:npm/foobar@1.2.3
jspm:git/org/repo@2.3.4

# mostly work like `file:`
# do not need to read `package.json`
# verbose
jspm:jspm_packages/npm/foobar@1.2.3
jspm:jspm_packages/git/org/repo@2.3.4
```

**Comment by blakeembrey** [comment]
I like either pointing to the package location (`jspm:npm/foobar@1.2.3`) or the first option of parsing it out of `package.json` and the config file.

**Comment by johnnyreilly** [comment]
I feel the same.

**Comment by unional** [comment]
**Draft, no need to comment on yet**

### jspm module metadata discovery

Files involved:
- package.json
- jspm.config.js
- jspm_packages/.dependencies.json

```ts
interface JspmModuleMetadata {
  configFiles: { [index: string]: string }
  packagesPath: string
  map: { [index: string]: string }
  paths: { [index: string]: string }
  dependencies: { [index: string]: {
    deps: { [index: string]: string }
    peerDeps: { [index: string]: string }
  }
}
```

#### Example

```ts
{
  configFiles: { "jspm": "<path to main config>", "jspm:node": "<path to node config>" }
  packagesPath: "custom_packages"
  map: { "lodash": "npm:lodash@4.13.1" }
  paths: { "npm:": "custom_packages/npm/", "github:": "custom_packages/github/" }
  dependencies: {
    "npm:lodash@4.13.1": {
      deps: {}
      peerDeps: { "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha" }
    },
    "github:jspm/nodelibs-buffer@0.2.0-alpha": {
      "deps": {
        "buffer-browserify": "npm:buffer@^4.0.0"
      },
      "peerDeps": {}
    },
    "npm:buffer@4.6.0": {
      "deps": {
        "base64-js": "npm:base64-js@^1.0.2",
        "ieee754": "npm:ieee754@^1.1.4",
        "isarray": "npm:isarray@^1.0.0"
      },
      "peerDeps": {
        "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha",
        "process": "github:jspm/nodelibs-process@^0.2.0-alpha"
      }
    },
    "npm:isarray@1.0.0": {
      "deps": {},
      "peerDeps": {}
    },
    "npm:ieee754@1.1.6": {
      "deps": {},
      "peerDeps": {
        "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha"
      }
    },
    "npm:base64-js@1.1.2": {
      "deps": {},
      "peerDeps": {}
    },
    "github:jspm/nodelibs-process@0.2.0-alpha": {
      "deps": {},
      "peerDeps": {}
    }
  }
}
```

**Comment by unional** [comment]
Just a thought, the typings dependencies should be separated from module dependencies...
a module depends on other modules does not necessarily mean its typings depends on those modules' typings.
Making such assumption cause `tsc` do a lot of extra work and consume a lot of memory with no benefits

What do you think? Should I bring this up to the TS team?

**Comment by blakeembrey** [comment]
@unional If I understand the question, you want a some sort of directive that'll tell the compiler it's a type definition only and not a module? That would certainly see some speed improvements for parsing, the more typings you currently install the slower it becomes. Really, I think https://github.com/Microsoft/TypeScript/issues/6427 might work for the issue - IIRC, the gist is that the TypeScript compiler could avoid trying to resolve modules if the declaration has already been found in the same file.

**Comment by unional** [comment]
I'm thinking how tsc (and us here) determine the dependencies typings need to be included or not. Tracing all the way down is not a feasible solution IMO

**Comment by unional** [comment]
Or efficient solution

**Comment by unional** [comment]
Or efficient solution

**Comment by unional** [comment]
Meaning, essentially what we have is a better solution. Having a `typings.json` (or embed it into `package.json`) that specifies which dependencies should be involved in the typings resolution.

**Comment by unional** [comment]
Let me expand on it a bit. My idea revolves solely around resolving typings for ts language service so it can be used on IDE, and not for compilation. i.e. Separating type definition tree produced by `tsc` and `tsc -d` (or how ts language service gets typings metadata). During compilation the whole tree is needed but for language service only types accessible by the user needs typings.

When the size of the project grows, the memory consumption of ts language service will be significant if it needs to know all typings for all modules all the time.

Therefore my previous comment is not exactly correct:
- `tsc` still needs to resolve all dependencies thus `package.json/typings` should remain as is.
- `ts language service` should resolves dependencies only if the said type is involved in some `export` expression/statement:

```ts
import domready = require('domready');
import { foo } from './foo';

export function boo(callback: foo) {
  domready(foo);
}
```

- `domready` should be resolved by `tsc` but not `ts language service`

**Comment by unional** [comment]
https://github.com/typings/core/issues/116#issuecomment-225341791 is ready to be commented upon.

/cc @guybedford

**Comment by unional** [comment]
@blakeembrey currently I can't inject the fixture into `parseDependency()` so I can't add test (as jspm needs to read files).

Don't want to make bigger change without talking to you first. Do you have any suggestion?

**Comment by blakeembrey** [comment]
I think this is reasonable. For `parseDependency` you shouldn't need any fixtures - it's just taking strings and making sure they can be understood. Do you mean the dependency resolution process? That can use the pattern you've already been using - just make a fixtures directory for JSPM and test it can resolve a module with a dependency. I think the Bower implementation is somewhat what you want, because you're working with a flatter tree right? It's mostly just recursive resolution with the cached bower path (in your case it'd be the configuration object) passed around.

**Comment by guybedford** [comment]
How is this proposal affected by the new TypeScript npm approach? Should we be aligning with jspm compatibility for that?

**Comment by unional** [comment]
FWIW, jspm support is not complete with the TypsScript npm approach. see
https://github.com/Microsoft/TypeScript/issues/9184#issuecomment-226366308
https://github.com/Microsoft/TypeScript/issues/6012

The issue is `tsc` can only natively resolve typings from npm (`node_modules`). Meaning the typings in the package installed by `jspm` (under `jspm_packages`) will not resolve automatically by `tsc`.

There is a `rootDirs` and `path` to partially support it, but as `jspm` embed the version in the folder name (which I think is a great thing), they cannot map `lodash` to `jspm_packages/npm/lodash@4.3.1/` without understanding how `jspm` works.

Having a hook in `tsc` (as mentioned in this comment https://github.com/Microsoft/TypeScript/issues/9184#issuecomment-226368532) could be a way to do it, but I think it is not on the table yet.

**Comment by guybedford** [comment]
@unional but can't we `System.import` typing files along with loading typescript files? That way the npm resolution would work through the jspm conversion of npm packages.

**Comment by guybedford** [comment]
The only alternative seems to be implementing full jspm resolution within typescript, which seems eluded to in the other issues.

**Comment by unional** [comment]
> can't we System.import typing files along with loading typescript files?

Not sure what you mean. Do you mean the consumer would do that manually?

**Comment by unional** [comment]
Oh, do you mean using `jspm` as a dependency? I don't think we can do that.

**Comment by guybedford** [comment]
That would be one option. Or if there was a resolver hook provided we could hook jspm in. Alternatively a jspm-specific approach could possibly be put together.

**Comment by aluanhaddad** [comment]
> but can't we System.import typing files along with loading typescript files? That way the npm resolution would work through the jspm conversion of npm packages.

@guybedford Perhaps I am misunderstanding your comment, but it seems that would only work at runtime. For example, it would work for the typechecking done by plugin-typescript, but it would not work at design time, e.g. in IDEs, because the TypeScript language service is not calling `System.import`. For example, plugin-typescript supports importing _.html_ files given, in the sense that it reports no type errors for them, but that does not help IDEs which talk to the language service.

I _think_ TypeScript could possibly provide an interface which allows a function to intercept the lookup process which adds a declaration file to the compilation context. Then a plugin could be written which could delegate to `System.import` and the compiler would simply fallback to it's default resolution strategy in the absence of any such plugin. 

The more I think about it the more it feels like installing type declaration files and resolving them should be decoupled. For example, imagine if a hypothetical web service which hosts declaration files for its it endpoints but does not wish to publish an npm package. A plugin could resolve these declarations by calling to the web service at design time and then downloading and caching the files without any installation required.

These are just some ideas, I'm not sure if they make sense...

**Comment by guybedford** [comment]
Certainly an external resolver hook would make things simpler. A resolver is just a promise returning the resolved URL taking the module name, and parent URL arguments - `normalize('./file.d.ts', 'file:///path/to/package/main.js') -> file:///path/to/package/main.d.ts` We export this as `require('jspm').setPackagePath('/path/to/project'); require('jspm').normalize` so it can be hooked in easily in these kinds of scenarios.

The alternative is to implement the full jspm resolution in typescript. For reference, the resolution algorithm is detailed at https://github.com/systemjs/systemjs/blob/599d89cbe9f4fb39a39f6c52b619cbd1f1da6ffc/docs/resolution-algorithm.md#resolution-specification as well.

**Comment by unional** [comment]
THe need is a bit different. Here we need to access the path to the package, as well as finding out its dependencies.

I assume `normalize()` would resolve to the main file of the package. I can see there is a lot of overlapping code. So maybe extracting those logic in a module `jspm-module-resolver` would help?

**Comment by blakeembrey** [comment]
Looks merged, finally 😄
