### ISSUE TITLE
Install hangs for a long time when no Internet connection available

### ISSUE THREAD

**Issue by zuzusik** [typings/core#117]
**Run script with no Internet connection:**
```es6
var typings = require('typings-core'),
    path = require('path');

typings.install({production: false, cwd: path.resolve('.')})
  .catch((err) => {
    console.log('Failed to install typings because of error:', err);
  });
```
**typings-core 0.3.1**
almost immediately logs error and exits

**typings-core 1.0.1**
hangs for ~1 minute then logs error
then hangs for up to 10 minutes and only then exits

OSX `10.11.5`
Node  `4.4.5`

**Comment by blakeembrey** [comment]
Thanks. Right now, it's probably because we moved to exponential back-off and we're not differentiating the error codes. I'll split the codes out a bit more in the HTTP request so we handle server issues vs client issues differently in terms of retries.

Reference for later: https://nodejs.org/api/errors.html.

**Comment by blakeembrey** [comment]
* `ENOTFOUND` (No)
* `ECONNREFUSED` (Yes)
* `ECONNRESET` (Yes)

Do you know of other request error codes that need handling?

**Comment by zuzusik** [comment]
Not sure what `(Yes)` and `(No)` means in your list, but if `(No)` means that error doesn't need to be handled then I must admit that in case of no Internet connection it logs exactly `ENOTFOUND` error.

**Comment by blakeembrey** [comment]
Yes, that's it - was just writing out which ones should retry and which shouldn't when it comes to request errors.

**Comment by zuzusik** [comment]
Ahh, gotcha. So now in case of `ENOTFOUND` it starts retrying. Then considering the behaviour I described I wonder when `typings.install` promise is rejected? As for me it should be rejected after all retries are done. If it already works this way, then what is going on during those next ~10 minutes after the rejection during which script just hangs?

**Comment by blakeembrey** [comment]
Hard to say. I'll try to look into it and add some logging to catch it. It's possible there's more requests trying to resolve still. The entire back-off settings should only take at most around 2 minutes.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/blakeembrey/popsicle-retry/commit/1b4c2fe12d87b562d1a138c74f706fe2b04921f8.
