### ISSUE TITLE
Paths inside index.d.ts when using cwd option

### ISSUE THREAD

**Issue by coel** [typings/core#143]
I am programmatically calling typings (using typings-core@1.4.1), something like:

```
    const typings = require("typings-core");
    typings.install({production: false, cwd: "src/ts"});
```

I end up with index.d.ts inside src/ts/typings looking like:

```
/// <reference path="src/ts/typings/globals/jquery/index.d.ts" />
```

I did a search and came across an issue that is fixed in the CLI: https://github.com/typings/typings/issues/392

If I do then run at the command line:

`typings install --cwd src/ts`

I get an index.d.ts looking like I want:

```
/// <reference path="globals/jquery/index.d.ts" />
```

Should these two behave differently?  I might be misunderstanding the relationship of "core".

**Comment by blakeembrey** [comment]
You should use a proper path and resolve it first. E.g. `path.join(__dirname, 'src/ts')`.

**Comment by coel** [comment]
Thanks for the quick reply.  That works out, cheers.

**Comment by blakeembrey** [comment]
No worries, glad it helped! I would always recommend resolving paths, relying on any other behaviour can introduce ill-intended side effects (E.g. what if you run the script from a different working directory and generated everything somewhere else?).
