### ISSUE TITLE
typings-core ^1.4.0 does n't work on Node 0.10 which breaks folks relying on semver 

### ISSUE THREAD

**Issue by kumaran-is** [typings/core#168]
typings-core ^1.6.0 worked on node 0.10 with strip-bom:"^2.0.0" and detect-indent:"^4.0.0"

with typings-core ^1.7.0 release, bumped strip-bom:"^3.0.0" and detect-indent:"^5.0.0"  that uses ES6 features and dropped node 0.10 support

By doing this, libraries like typings which have a dependency chain on  typings-core(strip-bom and detect-indent) break when run on node 0.10.
This previously worked. 

I'm all for moving forward :), but I think the version should be changed to a new major version when dropping support for old node and ES.

I propose that typings-core <1.7.0  published with node 0 support should continue to support and  any version that dropping support should be bumped to new Major version

Future ... when we move to a new major version when dropping node support.

What do you think?

cc @kodypeterson

**Comment by blakeembrey** [comment]
See https://github.com/typings/core/issues/152. It was unpublished months ago.

**Comment by blakeembrey** [comment]
I can't see any possible reason you'd be installing or using `1.7.0`. If you are using it somehow, please let me know how you are installing it.

**Comment by kumaran-is** [comment]
Thanks . It was caching issue at our sinopia registry , after clearing unpublished  versions it started working.
