### ISSUE TITLE
Does not resolve by folder name

### ISSUE THREAD

**Issue by Delagen** [typings/core#170]
make typings of @angular/core@4.0.0-beta.7

does not resolve
in @angular/core/src/errors.d.ts 
```
import { DebugContext } from './view';
```

change to 
```
import { DebugContext } from './view/index';
```

makes it works

**Comment by blakeembrey** [comment]
It hasn't for a long time and has been a long open issue. Someone is free to fix it, but since the world is moving to `@types` I have been happy leaving it as is. See issue tracked at https://github.com/typings/typings/issues/173.

**Comment by Delagen** [comment]
`@types` is for manually written types. Bundle is for bundle typings in single file.

**Comment by blakeembrey** [comment]
I don't understand your comment, maybe you should elaborate on it? Why do you need to bundle with Typings? Usually that's only for testing locally, making sure the bundle is going to be valid when used elsewhere.

**Comment by Delagen** [comment]
For example: module typings bundle make easier to write typescript, when base module located outside direct module resolution, i.e. resolved via bundler such as webpack. I build typing bundles of angular to eliminate need to install it locally in every project

**Comment by blakeembrey** [comment]
But, in that case, can't you just rely on the dependency on Angular to be resolved naturally using TypeScript? TypeScript has always resolved native modules with definitions in their `package.json`. The disadvantage of using Typings here is that it breaks the reason Typings was written - to avoid dependency conflicts and use external modules (bundling results in a global definitions with a hard-coded global name that can conflict now).

**Comment by Delagen** [comment]
Typings bundle solve the issue that you can compile typings and write code without base module install with full type checking. I know that I can use `paths` option, but It separate case.

**Comment by Delagen** [comment]
https://github.com/typings/core/pull/171
