### ISSUE TITLE
All of 0 tests passed!

### ISSUE THREAD

**Issue by johnnyreilly** [typings/core#38]
Heya,

I just noticed that this is the output for running `test-cov` on Windows:

```
> typings-core@0.2.8 test-cov C:\source\core
> ts-node node_modules/istanbul/lib/cli.js cover -e .ts --print none -x '*.d.ts' -x '*.spec.ts' node_modules/blue-tape/b
in/blue-tape.js -- 'src/**/*.spec.ts' | tap-diff

No coverage information was collected, exit without writing coverage information

passed: 0  failed: 0  of 0 tests  (793ms)

All of 0 tests passed!
```

That's not desirable I guess?

This looks to be the result of the `test-spec` task: `ts-node node_modules/blue-tape/bin/blue-tape.js 'src/**/*.spec.ts' | tap-diff`

This was working on my Windows machine only a couple of days ago...

**Comment by johnnyreilly** [comment]
I think it's the single quotes that screw it up.  So this works:

How come `npm run test` doesn't include `npm run test-spec`? Is that intentional?

**Comment by blakeembrey** [comment]
`npm test` runs the code coverage version of the specs. Both `test-cov` and `test-spec` are the same test suite. `test-spec` is there for personal reasons, if tests with coverage are slower than you wish.

**Comment by blakeembrey** [comment]
We've got failing tests now... so that's an improvement  :tada:
