### ISSUE TITLE
The bang scheme doesn't work?

### ISSUE THREAD

**Issue by unional** [typings/core#55]
```sh
typings i npm!angular@1.1.1
-bash: !angular@1.1.1: event not found
```

May need to choose a different symbol?

**Comment by blakeembrey** [comment]
Use quotes for bash.

**Comment by blakeembrey** [comment]
Feel free to suggest a better symbol though, we can roll it into breaking changes for 1.0.

**Comment by unional** [comment]
Tried and using quotes is working. Thanks.
I was thinking about sending a PR to add that in the help text. But realize why I didn't *feel good* about the bang scheme:

In my mind the "!" signifies that we are going up in the internet to get typings, vs `npm:<>`, `bower:<>`, and `file:<>` which resolves locally.

However, ":" scheme for github, bitbucket, and http(s) are already accessing the internet.

I think that is *my* root cause.

Do you have a different way to think about the schemes that is uniform across the board?

**Comment by blakeembrey** [comment]
Schemes are ways to resolve information that has been defined by typings (E.g. we have `registry:` to also resolve to the registry). The bang scheme is only a shorthand, expanding `dt!domready` to `registry:dt!domready`. This is useful since the default source can then be defined as `npm`, so when you omit the source location it'll use the default. As a result, `domready` expands to `registry:npm/domready`.

**Comment by unional** [comment]
Good point. But I think that adds a bit more confusion:

* `domready` => `registry:npm/domready` (given `defaultSource = npm`)
* `npm:domready` => `npm:domready` (resolves locally)
* `npm!domready` => `registry:npm/domready` (notice ! replaced as /)
* `dt!domready` => `registry:dt!domready` (notice ! is not replaced as /, because dt does not exists in `registry:`)
  * I was thinking `dt!domready` => `dt:domready` + resolves through internet (as in `github:`)

or, on the other hand, maybe there shouldn't be `dt!domready`, only `dt:domready`? In this case, the syntax is clear:
* `<source>!` is a pure sugar for `registry:<source>/`
* `{file,github,bitbucket,npm,bower,http(s),dt,registry}:` are different "endpoint" schemes (using the word "endpoint" instead of "registry" to avoid confusion).

**Comment by blakeembrey** [comment]
@unional Sorry, the last bullet was a typo by me. It is replaced with a slash. Updated it above.

**Comment by blakeembrey** [comment]
The "syntax is clear" summary is correct. Though we have no `dt:` scheme, it's `github:DefinitelyTyped/DefinitelyTyped`.

**Comment by unional** [comment]
I see. I would then suggest to add the `dt:` scheme that maps to `github:DefinitelyTyped/DefinitelyTyped`. Because if user needs to do `typings install dt!domready` (desugar to `typings install registry:dt/domready`), it seems like the user needs to know too much on how things work.

In user's perspective:
* `<endpoint>:` is "Where I want to get the typings from".
* `registry:dt/domready` means typings/registry has typings under <term> (source? distribution channel? this part is still not clear), but in fact it is not. The registry (typings/api) just internally resolves it to DT/DT.

**Comment by blakeembrey** [comment]
> The registry (typings/api) just internally resolves it to DT/DT.

But it may not _always_. That's the major point. This is future compatible with the NPM discussion, where the registry may indeed be also serving the content (E.g. using NPM as the registry endpoint).

**Comment by unional** [comment]
Make sense. But will that happen? What I mean is putting DT under `@typed/dt_domready`. We should eventually break away from DT, so "taking it off the side" might be a good idea. :smile: 

As for replacing "!" to avoid the bash issue, how about "::"? Or even without? i.e. `typings install npm/domready`, `typings install env/atom`. (yes, this again conflict with the `defaultSource`)

**Comment by blakeembrey** [comment]
You can't use slash because then it can't disambiguate between github typings, scoped NPM typings and wanting to use a source. Hence the need for some other character to make it easier. Otherwise we'd just have no defaults, but I think that's even more confusing.

**Comment by unional** [comment]
> it can't disambiguate between github typings, scoped NPM typings and wanting to use a source.

Not sure I understand. github (`typings install github:abc/def`), npm (`typings install npm:domready/scope`).

The "without" suggestion is that `typings i npm/domready` will desugar to `typings i registry:npm/domready`.
If you consider that it conflicts with `defaultSource`, then yes, it does.

How about "::" suggestion? `typings i npm::domready` desugar to `typings i registry:npm/domready`.

**Comment by blakeembrey** [comment]
> If you consider that it conflicts

Yes, this. I have no issue with the double colon, but it seems more ambiguous. I'd prefer a different symbol to avoid confusion (E.g. avoid issues where "was it `:` or `::` that you used?).

**Comment by unional** [comment]
Several options that works in bash: "~", "%", "^", "+".

**Comment by unional** [comment]
"^" does not work on powershell

**Comment by blakeembrey** [comment]
Using `+` is not bad, `env+atom`. What a PITA...

**Comment by glen-84** [comment]
`+` seems okay, or just `--src=env` or similar.

**Comment by blakeembrey** [comment]
@glen-84 That's actually how it used to work pre-0.7. However, that doesn't really scale to multiple installations: `typings install env!node npm!debug`.

**Comment by glen-84** [comment]
True, I didn't think about that.
