### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by unional** [typings/core#59]
Just a thought:
If the source package contains test code, is it possible to get the test code as `.ts` and compile against them to catch any signature mismatch?

**Comment by blakeembrey** [comment]
Yes, it's possible - especially with the new `--allowJs`, this should actually work.

**Comment by unional** [comment]
Using https://github.com/typed-typings/npm-batch as a test. Here are the findings:
* just `--allowJs` won't work. `tsc` just bypass them. No type checking there.
* Need to copy the file as `.ts` and make some small changes (e.g. `var` to `import`). See https://github.com/typed-typings/npm-batch/tree/master/source-test
* Since now there are tests from the source and tests you write yourself, it's better to put bundled typings in a neutral location (`npm run build` => `typings bundle -o out`). Then both `test` and `source-test` can reference them much the same way.
* I started using `git submodule add <source> source` so that I can easily reference the source package (can copy any test over)
* Different sources might use different test harness, so automation (`generator-typings`) would be hard. Some basic plumbing work is still possible.

**Comment by unional** [comment]
* Definitely want `tslint` `exclude` feature (in `tslint.json`). Life is too short to fix other people's styling (exclude `source` and `source-test`)

**Comment by blakeembrey** [comment]
Ah, now I see why stuff was changed. Should use branches. Sorry, going in reverse through my emails. As for the `.js` bypassing them, we should be able to make it do some type checking. I've noticed working in VSCode that there's basic type checking of my `.js` files, so there's a flag somewhere to make it happen.

**Comment by unional** [comment]
> I've noticed working in VSCode that there's basic type checking of my .js files,

That's `salsa` in working, not `tsc`. If we can tap into that, then yes. :smile:

**Comment by blakeembrey** [comment]
Right, but the Salsa effort is part of `tsc` currently. So there should be a way... :smile:

**Comment by unional** [comment]
> Right, but the Salsa effort is part of tsc currently. So there should be a way...

Let's file an issue. :smile: Can't find an option on cli

**Comment by unional** [comment]
https://github.com/Microsoft/TypeScript/issues/7661

**Comment by unional** [comment]
With the `source` test completed on `npm-chai`, we can close this issue and open an action item for the future.
