### ISSUE TITLE
Duplicated build steps?

### ISSUE THREAD

**Issue by unional** [typings/core#65]
Saw logs like these repeated many times in Travis CI:

> typings-core@0.2.11 prepublish /home/travis/build/typings/core
> node scripts/prepublish.js
> 
> typings-core@0.2.11 build /home/travis/build/typings/core
> rimraf dist && tsc

I thought my PR causes it but actually it is not. Something wrong?

**Comment by blakeembrey** [comment]
Is it just `rimraf dist && tsc`? This is because it's a part of both `test` and `prepublish`. I'm indifferent toward fixing it, but you're welcome to take a look. Maybe test shouldn't build?

**Comment by unional** [comment]
On average each build for each node target takes about 1:30 to complete. When I look into the build, saw a whole bunch of these. Don't know if it is just log rendering issue on travis and appveyor

**Comment by blakeembrey** [comment]
No, it does occur multiple times. It's because `prepublish` is run when `npm install` occurs and `build` is run before tests. So one of those is technically unnecessary. There's also a build as part of bootstrapping that occurs, but that one is a weak build (maybe failed, can't tell because it's to bootstrap installing the type definitions).

**Comment by unional** [comment]
> it does occur multiple times ...

Yes, understand your reasoning. But at the same time, they appear thousands of times:
https://travis-ci.org/typings/core/jobs/118619910
So I guess that IS log rendering issue?

Will give it a try on simplify the commands

**Comment by blakeembrey** [comment]
That seems like a bug, some issue with the environment variable setting I guess. I noticed it first when @johnnyreilly pointed it out when merging the new script, but it's been intermittent enough and things work.

**Comment by johnnyreilly** [comment]
Oddly enough I seem to remember it occuring massively on node 0.10 but less so in newer nodes. Though my memory may be playing tricks on me..
