### ISSUE TITLE
suggestion: use `exclude` for root `tsconfig.json`

### ISSUE THREAD

**Issue by unional** [typings/core#73]
While `files` works for `tsc`, it doesn't work well for `language service`. Currently `*.spec.ts` does not get typings info because `src/typings.ts` does not resolve to those files.

Can rename current `tsconfig.json` to `tsconfig.build.json` and `package.json/scripts/build: rimraf dist && tsc -p tsconfig.build.json`

I don't know which files should be excluded, but I guess it would be this:
```js
{
  "compilerOptions": {
    "noLib": false
  },
  "excludes": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts",
    "dist"
  ]
}
```
If you are ok with that, I can create a PR. :smile:

**Comment by blakeembrey** [comment]
I don't like `exclude`, sorry. Maintaining blacklists over whitelists has always ended in pain for me, so I'm mostly waiting for `include` to fix this properly.

**Comment by unional** [comment]
Closing. Will wait for `include`

**Comment by unional** [comment]
However, for `tsc`, `files` is still the best option IMO. 
https://github.com/palantir/tslint/pull/857#issuecomment-204060990
