### ISSUE TITLE
Break `npm test` into two

### ISSUE THREAD

**Issue by unional** [typings/core#74]
One for development: `npm run build && npm run test-cov`.
One for CI: (current one).

So that test can be run much faster during development.

**Comment by unional** [comment]
Or maybe I should just use `npm run test-spec` during development instead? :smile:

**Comment by blakeembrey** [comment]
Yes, `test-spec` is normally what I write to provide a lighter weight test script. Normally it doesn't do as much as `test` (which is complete) and is faster because it skips things like code coverage.

**Comment by unional** [comment]
Closing this discussion. Use `test-spec`
