### ISSUE TITLE
Create DT scheme

### ISSUE THREAD

**Issue by unional** [typings/core#82]
Talked about it in some of the threads. Couldn't find it.

Making this the "official" discussion for this topic.

Currently using `--ambient` flag also for DT is confusing.
As not all DT typings are "ambient". The have `declare module "xxx"`, but not necessary `declare namespace xxx` or `declare module xxx`.

**Comment by choeller** [comment]
The fact I need to add the `--ambient` flag when wanting to install from DT added to my confusion I described here: https://github.com/typings/typings/issues/343 so I would also upvote another wording here ;)

**Comment by unional** [comment]
For records, there are several types of typings exists today:

## global / script typings
These are typings that pollutes the global namespace.
They have `declare namespace xxx` or `declare module xxx` and does not have top-level `import`/`export`
Both DT and `typings/registry` can have these

## top level module typings
They are typings that do not pollute global namespace and have top-level `import`/`export` statements.
They do not wrap inside `declare module "xxx"`.
These are typings registered in `typings/registry`.

### Wrapped module typings
They are typings that do not pollute global namespace and have do not have top-level `import`/`export` statements.
They wrap their declarations inside `declare module "xxx"`.
These are typings in DT.

**Comment by unional** [comment]
https://github.com/typings/typings/pull/400

**Comment by unional** [comment]
This scheme is mentioned here: https://github.com/typings/core/issues/3#issuecomment-180642530

I recall there is one more place that mention this. But can't find it.

**Comment by blakeembrey** [comment]
@unional Can you elaborate? It sounds like it's how it already works, so I'm confused.

**Comment by blakeembrey** [comment]
Or you mean `dt:` scheme? What's the value of that? What's it do? Can you spec the behaviour?

**Comment by unional** [comment]
Actually the `dt!` scheme.

> Can you spec the behaviour?

Sure. Here it is:

# Problem Statement
Currently using DT as a fallback option for `--ambient` flag is confusing.
The problem partially rooted from the definition of the term "ambient".
In general discussion, we use the term "ambient" for anything that is "non-module", i.e. it alters the environment.

For example `env` typings as in https://github.com/typings/registry/tree/master/env.

However, typings in DT does not necessary fit to that definition, as they can be "module" wrapped inside `declare module "domready" { }`.

Therefore, letting (and educating) user to do `typings install ABC --ambient` when they want to install typings form DT adds confusion to the term `ambient`. This effect is huge because currently we still rely on typings in DT most of the time.
The same applies when we rename `ambient` to `global` or `script`.

## Proposal
- Current behavior: `typings install domready --ambient` maps to `typings install registry:dt/domready` as last resort
- New behavior: Remove the above behavior and tell user to always do `typings install dt!domready` instead.

To remove this behavior, we might need to address this first: https://github.com/typings/core/issues/55
Also, maybe further improve the help text would be useful (doubt not many user aware of the `dt!` syntax):

```sh
typings install [<name>=]<location>

  <name>      Module name of the installed definition
  <location>  The location to read from (described below)

Valid Locations:
  [<source>!]<pkg>[@<version>][#<tag>]    <---- very not easy to catch the "!" vs ":"
  file:<path>
  github:<org>/<repo>[/<path>][#<commitish>]
  bitbucket:<org>/<repo>[/<path>][#<commitish>]
  npm:<pkg>[/<path>]
  bower:<pkg>[/<path>]
  http(s)://<host>/<path>

  <source>    The registry mirror (E.g. "npm", "bower", "env", "global", "dt", ...)
```

Does it help? :beer:

**Comment by blakeembrey** [comment]
Isn't this the same issue as your previous one - https://github.com/typings/typings/issues/321?

**Comment by blakeembrey** [comment]
Sorry for making you write that all up if it is, but I agree. It would help for education, but will be terrible for all existing docs - just like changing the `--ambient` flag...

**Comment by unional** [comment]
lol, yeah, lost tracked on what is recorded and what is not. :smirk:

So we DID discuss about it. hehe.

**Comment by unional** [comment]
And it is all fine. I think this is better written the my last one. Going to update it and close this.

**Comment by unional** [comment]
Updated and close
