### ISSUE TITLE
Support comment in json

### ISSUE THREAD

**Issue by unional** [typings/core#90]
Do you want to use this implementation:
https://github.com/palantir/tslint/blob/master/src/utils.ts#L39

or https://github.com/sindresorhus/strip-json-comments?

**Comment by blakeembrey** [comment]
Definitely 2. Using a RegExp is pretty jank.

**Comment by blakeembrey** [comment]
However, why would we support comments? I don't think we want to.

**Comment by blakeembrey** [comment]
Closing as I don't want to support it. I know I mentioned it was possible, but I don't want to implement a ton of logic around keeping comments between rewrites.
